-- sintaxis
BEGIN
  DBMS_FGA.DROP_POLICY(
    object_schema => 'BANCO_CORE',
    object_name   => 'CUENTAS',
    policy_name   => 'FGA_CUENTAS_SALDO_ALTO'
  );
END;
/
--eleiminar 4 politicas
BEGIN
  DBMS_FGA.DROP_POLICY('BANCO_CORE', 'CUENTAS', 'FGA_CUENTAS_SALDO_ALTO');
  DBMS_FGA.DROP_POLICY('BANCO_CORE', 'CUENTAS', 'FGA_CUENTAS_MOD_SALDO');
  DBMS_FGA.DROP_POLICY('BANCO_CORE', 'TRANSFERENCIAS', 'FGA_TRANSFERENCIA_MONTO_ALTO');
  DBMS_FGA.DROP_POLICY('BANCO_CORE', 'CLIENTES', 'FGA_CLIENTES_DATOS_SENSIBLES');
END;
/

-- desactivar
BEGIN
  DBMS_FGA.DISABLE_POLICY('BANCO_CORE', 'CUENTAS', 'FGA_CUENTAS_SALDO_ALTO');
END;
/
-- acivar 

BEGIN
  DBMS_FGA.ENABLE_POLICY('BANCO_CORE', 'CUENTAS', 'FGA_CUENTAS_SALDO_ALTO');
END;
/



-- modifica

BEGIN
  DBMS_FGA.DROP_POLICY('BANCO_CORE', 'TRANSFERENCIAS', 'FGA_TRANSFERENCIA_MONTO_ALTO');

  DBMS_FGA.ADD_POLICY(
    object_schema   => 'BANCO_CORE',
    object_name     => 'TRANSFERENCIAS',
    policy_name     => 'FGA_TRANSFERENCIA_MONTO_ALTO',
    audit_condition => 'MONTO > 20000',
    audit_column    => 'MONTO',
    statement_types => 'INSERT,UPDATE',
    enable          => TRUE
  );
END;
/



--- verificar politicas 
SELECT OBJECT_NAME, POLICY_NAME, ENABLED
FROM DBA_AUDIT_POLICIES
WHERE OBJECT_SCHEMA = 'BANCO_CORE'
ORDER BY OBJECT_NAME, POLICY_NAME;