/*==============================================================================
  SISTEMA BANCARIO DE TRANSFERENCIAS - ORACLE XE 21c
  VERSIÓN 1 - SEPARACIÓN DE ESQUEMAS: BANCO_CATALOGO / BANCO_CORE

==============================================================================*/


--==============================================================================
-- PASO 1: Permitir crear usuarios sin restricciones de contraseña
--==============================================================================

ALTER SESSION SET "_ORACLE_SCRIPT" = true;


--==============================================================================
-- PASO 2: Crear los dos esquemas
--==============================================================================

CREATE USER BANCO_CATALOGO IDENTIFIED BY 4009;
ALTER USER BANCO_CATALOGO QUOTA UNLIMITED ON USERS;
GRANT RESOURCE TO BANCO_CATALOGO;

CREATE USER BANCO_CORE IDENTIFIED BY 4009;
ALTER USER BANCO_CORE QUOTA UNLIMITED ON USERS;
GRANT RESOURCE TO BANCO_CORE;

-- Verificar usuarios
SELECT USERNAME, ACCOUNT_STATUS FROM DBA_USERS
WHERE USERNAME IN ('BANCO_CATALOGO', 'BANCO_CORE');


--==============================================================================
-- PASO 3: Tablas de catálogo (esquema BANCO_CATALOGO)
--==============================================================================

CREATE TABLE BANCO_CATALOGO.ROLES_SISTEMA (
    ID_ROL          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE_ROL      VARCHAR2(50) NOT NULL UNIQUE,
    DESCRIPCION     VARCHAR2(200)
);

CREATE TABLE BANCO_CATALOGO.TIPOS_DOCUMENTO (
    ID_TIPO_DOCUMENTO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE_TIPO       VARCHAR2(30) NOT NULL UNIQUE,
    DESCRIPCION       VARCHAR2(200)
);

CREATE TABLE BANCO_CATALOGO.TIPOS_CUENTA (
    ID_TIPO_CUENTA NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE_TIPO    VARCHAR2(30) NOT NULL UNIQUE,
    DESCRIPCION    VARCHAR2(200)
);

CREATE TABLE BANCO_CATALOGO.TIPOS_MOVIMIENTO (
    ID_TIPO_MOVIMIENTO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE_TIPO        VARCHAR2(40) NOT NULL UNIQUE,
    DESCRIPCION        VARCHAR2(200)
);

CREATE TABLE BANCO_CATALOGO.ESTADOS_TRANSFERENCIA (
    ID_ESTADO_TRANSFERENCIA NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE_ESTADO           VARCHAR2(30) NOT NULL UNIQUE,
    DESCRIPCION             VARCHAR2(200)
);


--==============================================================================
-- PASO 4: Privilegios cruzados de BANCO_CATALOGO hacia BANCO_CORE
--==============================================================================
-- REFERENCES es obligatorio para poder crear las FK en BANCO_CORE.

GRANT REFERENCES, SELECT ON BANCO_CATALOGO.ROLES_SISTEMA          TO BANCO_CORE;
GRANT REFERENCES, SELECT ON BANCO_CATALOGO.TIPOS_DOCUMENTO        TO BANCO_CORE;
GRANT REFERENCES, SELECT ON BANCO_CATALOGO.TIPOS_CUENTA           TO BANCO_CORE;
GRANT REFERENCES, SELECT ON BANCO_CATALOGO.TIPOS_MOVIMIENTO       TO BANCO_CORE;
GRANT REFERENCES, SELECT ON BANCO_CATALOGO.ESTADOS_TRANSFERENCIA  TO BANCO_CORE;


--==============================================================================
-- PASO 5: Tablas transaccionales (esquema BANCO_CORE)
--==============================================================================

--==============================================================================
-- 5.1 CLIENTES
--==============================================================================

CREATE TABLE BANCO_CORE.CLIENTES (
    ID_CLIENTE         NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_TIPO_DOCUMENTO  NUMBER NOT NULL
        REFERENCES BANCO_CATALOGO.TIPOS_DOCUMENTO(ID_TIPO_DOCUMENTO),
    NUMERO_DOCUMENTO   VARCHAR2(30) NOT NULL UNIQUE,
    NOMBRES            VARCHAR2(100) NOT NULL,
    APELLIDOS          VARCHAR2(100) NOT NULL,
    CORREO             VARCHAR2(150) UNIQUE,
    TELEFONO           VARCHAR2(30),
    ESTADO             CHAR(1) DEFAULT 'A' NOT NULL,
    FECHA_REGISTRO     TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT CK_CLIENTE_ESTADO CHECK (ESTADO IN ('A','I'))
);


--==============================================================================
-- 5.2 USUARIOS_SISTEMA
--==============================================================================

CREATE TABLE BANCO_CORE.USUARIOS_SISTEMA (
    ID_USUARIO       NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_ROL           NUMBER NOT NULL
        REFERENCES BANCO_CATALOGO.ROLES_SISTEMA(ID_ROL),
    NOMBRE_USUARIO   VARCHAR2(50) NOT NULL UNIQUE,
    NOMBRE_COMPLETO  VARCHAR2(150) NOT NULL,
    CORREO           VARCHAR2(150),
    ESTADO           CHAR(1) DEFAULT 'A' NOT NULL,
    FECHA_CREACION   TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT CK_USUARIO_ESTADO CHECK (ESTADO IN ('A','I'))
);


--==============================================================================
-- 5.3 CUENTAS
--==============================================================================


CREATE TABLE BANCO_CORE.CUENTAS (
    ID_CUENTA           NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_CLIENTE          NUMBER NOT NULL
        REFERENCES BANCO_CORE.CLIENTES(ID_CLIENTE),
    ID_TIPO_CUENTA      NUMBER NOT NULL
        REFERENCES BANCO_CATALOGO.TIPOS_CUENTA(ID_TIPO_CUENTA),
    NUMERO_CUENTA       VARCHAR2(30) NOT NULL UNIQUE,
    SALDO               NUMBER(18,2) DEFAULT 0 NOT NULL,
    ESTADO              CHAR(1) DEFAULT 'A' NOT NULL,
    FECHA_APERTURA      DATE DEFAULT SYSDATE,
    FECHA_ULTIMA_MOD    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT CK_CUENTAS_SALDO  CHECK (SALDO >= 0),
    CONSTRAINT CK_CUENTAS_ESTADO CHECK (ESTADO IN ('A','I'))
);


--==============================================================================
-- 5.4 TRANSFERENCIAS
--==============================================================================

CREATE TABLE BANCO_CORE.TRANSFERENCIAS (
    ID_TRANSFERENCIA        NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_CUENTA_ORIGEN        NUMBER NOT NULL
        REFERENCES BANCO_CORE.CUENTAS(ID_CUENTA),
    ID_CUENTA_DESTINO       NUMBER NOT NULL
        REFERENCES BANCO_CORE.CUENTAS(ID_CUENTA),
    MONTO                    NUMBER(18,2) NOT NULL,
    ID_ESTADO_TRANSFERENCIA NUMBER NOT NULL
        REFERENCES BANCO_CATALOGO.ESTADOS_TRANSFERENCIA(ID_ESTADO_TRANSFERENCIA),
    FECHA_TRANSACCION       TIMESTAMP DEFAULT SYSTIMESTAMP,
    ID_USUARIO               NUMBER
        REFERENCES BANCO_CORE.USUARIOS_SISTEMA(ID_USUARIO),
    CONSTRAINT CK_TRANSFERENCIA_MONTO   CHECK (MONTO > 0),
    CONSTRAINT CK_TRANSFERENCIA_CUENTAS CHECK (ID_CUENTA_ORIGEN <> ID_CUENTA_DESTINO)
);


--==============================================================================
-- 5.5 MOVIMIENTOS_CUENTA
--==============================================================================

CREATE TABLE BANCO_CORE.MOVIMIENTOS_CUENTA (
    ID_MOVIMIENTO       NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_CUENTA           NUMBER NOT NULL
        REFERENCES BANCO_CORE.CUENTAS(ID_CUENTA),
    ID_TIPO_MOVIMIENTO  NUMBER NOT NULL
        REFERENCES BANCO_CATALOGO.TIPOS_MOVIMIENTO(ID_TIPO_MOVIMIENTO),
    DEBITO              NUMBER(18,2) DEFAULT 0 NOT NULL,
    CREDITO             NUMBER(18,2) DEFAULT 0 NOT NULL,
    SALDO_RESULTANTE    NUMBER(18,2) NOT NULL,
    FECHA               TIMESTAMP DEFAULT SYSTIMESTAMP,
    ID_TRANSFERENCIA    NUMBER
        REFERENCES BANCO_CORE.TRANSFERENCIAS(ID_TRANSFERENCIA),
    CONSTRAINT CK_MOV_DEBITO       CHECK (DEBITO >= 0),
    CONSTRAINT CK_MOV_CREDITO      CHECK (CREDITO >= 0),
    CONSTRAINT CK_MOV_SALDO        CHECK (SALDO_RESULTANTE >= 0),
    CONSTRAINT CK_MOV_TIPO_IMPORTE CHECK (
        (DEBITO > 0 AND CREDITO = 0)
        OR
        (CREDITO > 0 AND DEBITO = 0)
    )
);


--==============================================================================
-- 5.6 AUDITORIA
--==============================================================================

CREATE TABLE BANCO_CORE.AUDITORIA (
    ID_AUDITORIA NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_USUARIO   NUMBER
        REFERENCES BANCO_CORE.USUARIOS_SISTEMA(ID_USUARIO),
    ACCION       VARCHAR2(100),
    ENTIDAD      VARCHAR2(50),
    ID_ENTIDAD   NUMBER,
    DETALLE      VARCHAR2(1000),
    FECHA_HORA   TIMESTAMP DEFAULT SYSTIMESTAMP
);


--==============================================================================
-- PASO 6: Roles de base de datos
--==============================================================================

CREATE ROLE ROL_ADMIN_BANCO;
CREATE ROLE ROL_OPERADOR_TRANSFERENCIAS;
CREATE ROLE ROL_CONSULTA_BANCO;


--==============================================================================
-- 6.1 ROL_ADMIN_BANCO
--==============================================================================
-- Catálogos (esquema BANCO_CATALOGO)
GRANT SELECT, INSERT, UPDATE ON BANCO_CATALOGO.ROLES_SISTEMA         TO ROL_ADMIN_BANCO;
GRANT SELECT, INSERT, UPDATE ON BANCO_CATALOGO.TIPOS_DOCUMENTO       TO ROL_ADMIN_BANCO;
GRANT SELECT, INSERT, UPDATE ON BANCO_CATALOGO.TIPOS_CUENTA          TO ROL_ADMIN_BANCO;
GRANT SELECT, INSERT, UPDATE ON BANCO_CATALOGO.TIPOS_MOVIMIENTO      TO ROL_ADMIN_BANCO;
GRANT SELECT, INSERT, UPDATE ON BANCO_CATALOGO.ESTADOS_TRANSFERENCIA TO ROL_ADMIN_BANCO;

-- Tablas principales (esquema BANCO_CORE)
GRANT SELECT, INSERT, UPDATE ON BANCO_CORE.CLIENTES         TO ROL_ADMIN_BANCO;
GRANT SELECT, INSERT, UPDATE ON BANCO_CORE.USUARIOS_SISTEMA TO ROL_ADMIN_BANCO;
GRANT SELECT, INSERT, UPDATE ON BANCO_CORE.CUENTAS           TO ROL_ADMIN_BANCO;
GRANT SELECT, INSERT, UPDATE ON BANCO_CORE.TRANSFERENCIAS    TO ROL_ADMIN_BANCO;

-- Movimientos y auditoría
GRANT SELECT, INSERT ON BANCO_CORE.MOVIMIENTOS_CUENTA TO ROL_ADMIN_BANCO;
GRANT SELECT, INSERT ON BANCO_CORE.AUDITORIA          TO ROL_ADMIN_BANCO;


--==============================================================================
-- 6.2 ROL_OPERADOR_TRANSFERENCIAS
--==============================================================================
GRANT SELECT ON BANCO_CATALOGO.TIPOS_DOCUMENTO       TO ROL_OPERADOR_TRANSFERENCIAS;
GRANT SELECT ON BANCO_CATALOGO.TIPOS_CUENTA          TO ROL_OPERADOR_TRANSFERENCIAS;
GRANT SELECT ON BANCO_CATALOGO.TIPOS_MOVIMIENTO      TO ROL_OPERADOR_TRANSFERENCIAS;
GRANT SELECT ON BANCO_CATALOGO.ESTADOS_TRANSFERENCIA TO ROL_OPERADOR_TRANSFERENCIAS;

GRANT SELECT ON BANCO_CORE.CLIENTES                   TO ROL_OPERADOR_TRANSFERENCIAS;
GRANT SELECT, INSERT, UPDATE ON BANCO_CORE.CUENTAS    TO ROL_OPERADOR_TRANSFERENCIAS;
GRANT SELECT, INSERT ON BANCO_CORE.TRANSFERENCIAS     TO ROL_OPERADOR_TRANSFERENCIAS;
GRANT SELECT, INSERT ON BANCO_CORE.MOVIMIENTOS_CUENTA TO ROL_OPERADOR_TRANSFERENCIAS;


--==============================================================================
-- 6.3 ROL_CONSULTA_BANCO
--==============================================================================
GRANT SELECT ON BANCO_CATALOGO.TIPOS_DOCUMENTO       TO ROL_CONSULTA_BANCO;
GRANT SELECT ON BANCO_CATALOGO.TIPOS_CUENTA          TO ROL_CONSULTA_BANCO;
GRANT SELECT ON BANCO_CATALOGO.TIPOS_MOVIMIENTO      TO ROL_CONSULTA_BANCO;
GRANT SELECT ON BANCO_CATALOGO.ESTADOS_TRANSFERENCIA TO ROL_CONSULTA_BANCO;

GRANT SELECT ON BANCO_CORE.CLIENTES           TO ROL_CONSULTA_BANCO;
GRANT SELECT ON BANCO_CORE.CUENTAS            TO ROL_CONSULTA_BANCO;
GRANT SELECT ON BANCO_CORE.TRANSFERENCIAS     TO ROL_CONSULTA_BANCO;
GRANT SELECT ON BANCO_CORE.MOVIMIENTOS_CUENTA TO ROL_CONSULTA_BANCO;


--==============================================================================
-- PASO 7: Crear usuarios y asignar roles
--==============================================================================

CREATE USER USR_ADMIN_BANCO IDENTIFIED BY 4009;
GRANT CONNECT TO USR_ADMIN_BANCO;
GRANT ROL_ADMIN_BANCO TO USR_ADMIN_BANCO;

CREATE USER USR_OPERADOR1 IDENTIFIED BY 4009;
GRANT CONNECT TO USR_OPERADOR1;
GRANT ROL_OPERADOR_TRANSFERENCIAS TO USR_OPERADOR1;

CREATE USER USR_CONSULTA1 IDENTIFIED BY 4009;
GRANT CONNECT TO USR_CONSULTA1;
GRANT ROL_CONSULTA_BANCO TO USR_CONSULTA1;


--==============================================================================
-- PASO 8: Datos de ejemplo (catálogos)
--==============================================================================

INSERT INTO BANCO_CATALOGO.ROLES_SISTEMA (NOMBRE_ROL, DESCRIPCION)
VALUES ('ADMIN', 'Administrador del sistema');

INSERT INTO BANCO_CATALOGO.ROLES_SISTEMA (NOMBRE_ROL, DESCRIPCION)
VALUES ('OPERADOR', 'Ejecuta transferencias');

INSERT INTO BANCO_CATALOGO.ROLES_SISTEMA (NOMBRE_ROL, DESCRIPCION)
VALUES ('CONSULTA', 'Consulta información bancaria');

INSERT INTO BANCO_CATALOGO.TIPOS_DOCUMENTO (NOMBRE_TIPO, DESCRIPCION)
VALUES ('DPI', 'Documento Personal de Identificación');

INSERT INTO BANCO_CATALOGO.TIPOS_DOCUMENTO (NOMBRE_TIPO, DESCRIPCION)
VALUES ('PASAPORTE', 'Documento de pasaporte');

INSERT INTO BANCO_CATALOGO.TIPOS_CUENTA (NOMBRE_TIPO, DESCRIPCION)
VALUES ('MONETARIA', 'Cuenta monetaria');

INSERT INTO BANCO_CATALOGO.TIPOS_CUENTA (NOMBRE_TIPO, DESCRIPCION)
VALUES ('AHORRO', 'Cuenta de ahorro');

INSERT INTO BANCO_CATALOGO.TIPOS_CUENTA (NOMBRE_TIPO, DESCRIPCION)
VALUES ('CORRIENTE', 'Cuenta corriente');

INSERT INTO BANCO_CATALOGO.TIPOS_MOVIMIENTO (NOMBRE_TIPO, DESCRIPCION)
VALUES ('DEBITO', 'Salida de dinero');

INSERT INTO BANCO_CATALOGO.TIPOS_MOVIMIENTO (NOMBRE_TIPO, DESCRIPCION)
VALUES ('CREDITO', 'Entrada de dinero');

INSERT INTO BANCO_CATALOGO.ESTADOS_TRANSFERENCIA (NOMBRE_ESTADO, DESCRIPCION)
VALUES ('PENDIENTE', 'Transferencia pendiente');

INSERT INTO BANCO_CATALOGO.ESTADOS_TRANSFERENCIA (NOMBRE_ESTADO, DESCRIPCION)
VALUES ('COMPLETADA', 'Transferencia completada');

INSERT INTO BANCO_CATALOGO.ESTADOS_TRANSFERENCIA (NOMBRE_ESTADO, DESCRIPCION)
VALUES ('CANCELADA', 'Transferencia cancelada');

INSERT INTO BANCO_CATALOGO.ESTADOS_TRANSFERENCIA (NOMBRE_ESTADO, DESCRIPCION)
VALUES ('RECHAZADA', 'Transferencia rechazada');

COMMIT;


--==============================================================================
-- PASO 9: Datos de prueba (transaccionales)
--==============================================================================

INSERT INTO BANCO_CORE.USUARIOS_SISTEMA (ID_ROL, NOMBRE_USUARIO, NOMBRE_COMPLETO, CORREO)
VALUES (2, 'operador1', 'Operador Uno', 'operador@banco.com');

INSERT INTO BANCO_CORE.CLIENTES (ID_TIPO_DOCUMENTO, NUMERO_DOCUMENTO, NOMBRES, APELLIDOS, CORREO)
VALUES (1, '1000100010001', 'Juan', 'Pérez', 'juan@banco.com');

INSERT INTO BANCO_CORE.CLIENTES (ID_TIPO_DOCUMENTO, NUMERO_DOCUMENTO, NOMBRES, APELLIDOS, CORREO)
VALUES (1, '2000200020002', 'María', 'López', 'maria@banco.com');

INSERT INTO BANCO_CORE.CUENTAS (ID_CLIENTE, ID_TIPO_CUENTA, NUMERO_CUENTA, SALDO)
VALUES (1, 1, '001-0001', 5000);

INSERT INTO BANCO_CORE.CUENTAS (ID_CLIENTE, ID_TIPO_CUENTA, NUMERO_CUENTA, SALDO)
VALUES (2, 1, '001-0002', 1500);

COMMIT;


--==============================================================================
-- PASO 10: Verificaciones
--==============================================================================

-- Ver tablas por esquema
SELECT OWNER, TABLE_NAME FROM DBA_TABLES
WHERE OWNER IN ('BANCO_CATALOGO', 'BANCO_CORE')
ORDER BY OWNER, TABLE_NAME;

-- Ver catálogos
SELECT * FROM BANCO_CATALOGO.ROLES_SISTEMA;
SELECT * FROM BANCO_CATALOGO.TIPOS_DOCUMENTO;
SELECT * FROM BANCO_CATALOGO.TIPOS_CUENTA;
SELECT * FROM BANCO_CATALOGO.TIPOS_MOVIMIENTO;
SELECT * FROM BANCO_CATALOGO.ESTADOS_TRANSFERENCIA;

-- Ver clientes y cuentas
SELECT * FROM BANCO_CORE.CLIENTES;
SELECT * FROM BANCO_CORE.CUENTAS;

-- Ver privilegios cruzados de BANCO_CATALOGO hacia BANCO_CORE
SELECT GRANTOR, GRANTEE, TABLE_NAME, PRIVILEGE FROM DBA_TAB_PRIVS
WHERE GRANTOR = 'BANCO_CATALOGO' AND GRANTEE = 'BANCO_CORE'
ORDER BY TABLE_NAME, PRIVILEGE;

-- Ver privilegios del operador
SELECT GRANTEE, TABLE_NAME, PRIVILEGE FROM DBA_TAB_PRIVS
WHERE GRANTEE = 'ROL_OPERADOR_TRANSFERENCIAS'
ORDER BY TABLE_NAME;

-- Ver rol del usuario
SELECT GRANTEE, GRANTED_ROLE FROM DBA_ROLE_PRIVS
WHERE GRANTEE = 'USR_OPERADOR1';
