/*==============================================================================
  DATOS DE PRUEBA 
==============================================================================
*/
ALTER SESSION SET "_ORACLE_SCRIPT" = true;
SET SERVEROUTPUT ON;--sirve para mostrar en pantalla los mensajes que un bloque PL/SQL envía con DBMS_OUTPUT.PUT_LINE.

-- Asegurar roles de catálogo (por si se limpió solo CORE)
-- ID_ROL: 1=ADMIN, 2=OPERADOR, 3=CONSULTA (según proyecto_v1.sql)

-- 1) USUARIOS DE SISTEMA (3 tipos)
-- 1) USUARIOS DE SISTEMA (3 tipos)
INSERT INTO BANCO_CORE.USUARIOS_SISTEMA (ID_ROL, NOMBRE_USUARIO, NOMBRE_COMPLETO, CORREO, ESTADO)
SELECT 1, 'USR_ADMIN_BANCO', 'Administrador del Sistema', 'admin@banco.com', 'A'
FROM DUAL WHERE NOT EXISTS (
  SELECT 1 FROM BANCO_CORE.USUARIOS_SISTEMA WHERE UPPER(NOMBRE_USUARIO) = 'USR_ADMIN_BANCO'
);

INSERT INTO BANCO_CORE.USUARIOS_SISTEMA (ID_ROL, NOMBRE_USUARIO, NOMBRE_COMPLETO, CORREO, ESTADO)
SELECT 2, 'USR_OPERADOR1', 'Operador Uno', 'operador1@banco.com', 'A'
FROM DUAL WHERE NOT EXISTS (
  SELECT 1 FROM BANCO_CORE.USUARIOS_SISTEMA WHERE UPPER(NOMBRE_USUARIO) = 'USR_OPERADOR1'
);

INSERT INTO BANCO_CORE.USUARIOS_SISTEMA (ID_ROL, NOMBRE_USUARIO, NOMBRE_COMPLETO, CORREO, ESTADO)
SELECT 3, 'USR_CONSULTA1', 'Consultor Uno', 'consulta1@banco.com', 'A'
FROM DUAL WHERE NOT EXISTS (
  SELECT 1 FROM BANCO_CORE.USUARIOS_SISTEMA WHERE UPPER(NOMBRE_USUARIO) = 'USR_CONSULTA1'
);
COMMIT;
SELECT * FROM BANCO_CORE.USUARIOS_SISTEMA ;
-- ================================================================================================================
-- 2) CLIENTES
INSERT INTO BANCO_CORE.CLIENTES (ID_TIPO_DOCUMENTO, NUMERO_DOCUMENTO, NOMBRES, APELLIDOS, CORREO, TELEFONO)
SELECT 1, '1000100010001', 'Juan', 'Pérez', 'juan@banco.com', '5555-0001'
FROM DUAL WHERE NOT EXISTS (
  SELECT 1 FROM BANCO_CORE.CLIENTES WHERE NUMERO_DOCUMENTO='1000100010001'
);

INSERT INTO BANCO_CORE.CLIENTES (ID_TIPO_DOCUMENTO, NUMERO_DOCUMENTO, NOMBRES, APELLIDOS, CORREO, TELEFONO)
SELECT 1, '2000200020002', 'María', 'López', 'maria@banco.com', '5555-0002'
FROM DUAL WHERE NOT EXISTS (
  SELECT 1 FROM BANCO_CORE.CLIENTES WHERE NUMERO_DOCUMENTO='2000200020002'
);

INSERT INTO BANCO_CORE.CLIENTES (ID_TIPO_DOCUMENTO, NUMERO_DOCUMENTO, NOMBRES, APELLIDOS, CORREO, TELEFONO)
SELECT 1, '3000300030003', 'Carlos', 'García', 'carlos@banco.com', '5555-0003'
FROM DUAL WHERE NOT EXISTS (
  SELECT 1 FROM BANCO_CORE.CLIENTES WHERE NUMERO_DOCUMENTO='3000300030003'
);

INSERT INTO BANCO_CORE.CLIENTES (ID_TIPO_DOCUMENTO, NUMERO_DOCUMENTO, NOMBRES, APELLIDOS, CORREO, TELEFONO)
SELECT 1, '4000400040004', 'Ana', 'Martínez', 'ana@banco.com', '5555-0004'
FROM DUAL WHERE NOT EXISTS (
  SELECT 1 FROM BANCO_CORE.CLIENTES WHERE NUMERO_DOCUMENTO='4000400040004'
);

COMMIT;
SELECT * FROM BANCO_CORE.CLIENTES;
-- ================================================================================================================

-- 3) CUENTAS (saldos variados para fraude y sobregiros)
INSERT INTO BANCO_CORE.CUENTAS (ID_CLIENTE, ID_TIPO_CUENTA, NUMERO_CUENTA, SALDO, ESTADO)
SELECT c.ID_CLIENTE, 1, '001-0001', 15000, 'A'
FROM BANCO_CORE.CLIENTES c WHERE c.NUMERO_DOCUMENTO='1000100010001'
  AND NOT EXISTS (SELECT 1 FROM BANCO_CORE.CUENTAS WHERE NUMERO_CUENTA='001-0001');

INSERT INTO BANCO_CORE.CUENTAS (ID_CLIENTE, ID_TIPO_CUENTA, NUMERO_CUENTA, SALDO, ESTADO)
SELECT c.ID_CLIENTE, 1, '001-0002', 3500, 'A'
FROM BANCO_CORE.CLIENTES c WHERE c.NUMERO_DOCUMENTO='2000200020002'
  AND NOT EXISTS (SELECT 1 FROM BANCO_CORE.CUENTAS WHERE NUMERO_CUENTA='001-0002');

INSERT INTO BANCO_CORE.CUENTAS (ID_CLIENTE, ID_TIPO_CUENTA, NUMERO_CUENTA, SALDO, ESTADO)
SELECT c.ID_CLIENTE, 2, '001-0003', 8000, 'A'
FROM BANCO_CORE.CLIENTES c WHERE c.NUMERO_DOCUMENTO='3000300030003'
  AND NOT EXISTS (SELECT 1 FROM BANCO_CORE.CUENTAS WHERE NUMERO_CUENTA='001-0003');

INSERT INTO BANCO_CORE.CUENTAS (ID_CLIENTE, ID_TIPO_CUENTA, NUMERO_CUENTA, SALDO, ESTADO)
SELECT c.ID_CLIENTE, 1, '001-0004', 1200, 'A'
FROM BANCO_CORE.CLIENTES c WHERE c.NUMERO_DOCUMENTO='4000400040004'
  AND NOT EXISTS (SELECT 1 FROM BANCO_CORE.CUENTAS WHERE NUMERO_CUENTA='001-0004');

COMMIT;

SELECT * FROM BANCO_CORE.CUENTAS;
-- ================================================================================================================

-- Verificación
SELECT u.ID_USUARIO, r.NOMBRE_ROL, u.NOMBRE_USUARIO, u.NOMBRE_COMPLETO, u.ESTADO
FROM BANCO_CORE.USUARIOS_SISTEMA u
JOIN BANCO_CATALOGO.ROLES_SISTEMA r ON r.ID_ROL = u.ID_ROL
ORDER BY u.ID_USUARIO;

SELECT c.ID_CLIENTE, c.NOMBRES||' '||c.APELLIDOS AS CLIENTE,
       cu.NUMERO_CUENTA, cu.SALDO, cu.ESTADO
FROM BANCO_CORE.CLIENTES c
JOIN BANCO_CORE.CUENTAS cu ON cu.ID_CLIENTE = c.ID_CLIENTE
ORDER BY cu.NUMERO_CUENTA;