-- 1. Ver políticas creadas
SELECT OBJECT_SCHEMA, OBJECT_NAME, POLICY_NAME, ENABLED
FROM DBA_AUDIT_POLICIES
WHERE OBJECT_SCHEMA = 'BANCO_CORE'
ORDER BY POLICY_NAME;

-- 2. Probar UPDATE de SALDO (debe generar auditoría de FGA_CUENTAS_MOD_SALDO)
UPDATE BANCO_CORE.CUENTAS 
SET SALDO = 15000 
WHERE NUMERO_CUENTA = '001-0001';
COMMIT;

-- 3. Probar SELECT de saldo alto (debe generar auditoría de FGA_CUENTAS_SALDO_ALTO)
SELECT NUMERO_CUENTA, SALDO 
FROM BANCO_CORE.CUENTAS 
WHERE NUMERO_CUENTA = '001-0001';

-- 4. Probar INSERT de transferencia grande (debe generar auditoría de FGA_TRANSFERENCIA_MONTO_ALTO)
INSERT INTO BANCO_CORE.TRANSFERENCIAS 
  (ID_CUENTA_ORIGEN, ID_CUENTA_DESTINO, MONTO, ID_ESTADO_TRANSFERENCIA, ID_USUARIO)
VALUES (1, 2, 7000, 2, 1);
COMMIT;

-- 5. Probar SELECT de datos sensibles de clientes (debe generar auditoría de FGA_CLIENTES_DATOS_SENSIBLES)
SELECT NOMBRES, APELLIDOS, CORREO 
FROM BANCO_CORE.CLIENTES 
WHERE ID_CLIENTE = 1;

-- 6. Ver los registros de auditoría generados
SELECT DB_USER, 
       OBJECT_SCHEMA, 
       OBJECT_NAME, 
       POLICY_NAME, 
       SQL_TEXT, 
       TIMESTAMP
FROM DBA_FGA_AUDIT_TRAIL
WHERE OBJECT_SCHEMA = 'BANCO_CORE'
ORDER BY TIMESTAMP DESC;