-- Debe fallar ORA-20001
BEGIN
  UPDATE BANCO_CORE.CUENTAS SET SALDO = -500 WHERE NUMERO_CUENTA='001-0002';
EXCEPTION WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE(SQLERRM); ROLLBACK;
END;
/
-- Debe auditar
UPDATE BANCO_CORE.CUENTAS SET SALDO = 4000 WHERE NUMERO_CUENTA='001-0002';
COMMIT;
SELECT * FROM BANCO_CORE.AUDITORIA ORDER BY FECHA_HORA DESC FETCH FIRST 5 ROWS ONLY;