-- Sesión A:
UPDATE BANCO_CORE.CUENTAS SET SALDO = SALDO - 10 WHERE ID_CUENTA = 1;
-- Sesión B:
UPDATE BANCO_CORE.CUENTAS SET SALDO = SALDO - 10 WHERE ID_CUENTA = 2;
-- Sesión A:
UPDATE BANCO_CORE.CUENTAS SET SALDO = SALDO - 10 WHERE ID_CUENTA = 2;  -- espera
-- Sesión B:
UPDATE BANCO_CORE.CUENTAS SET SALDO = SALDO - 10 WHERE ID_CUENTA = 1;  -- deadlock ORA-00060